
export enum ActionType {
    STATISTICS_GET_STATISTICS = "STATISTICS_GET_STATISTICS",
    STATISTICS_DELETE_STATISTICS = "STATISTICS_DELETE_STATISTICS",
    STATISTICS_UPDATE_STATISTICS = "STATISTICS_UPDATE_STATISTICS",
    STATISTICS_TEST = "STATISTICS_TEST",

}