
/**
 * @const SET_MONTH_STRING Получить месяц года из DatePicker. Значение нужно для хука useToGetWeeks.
 * @const SET_TIME_STEP Получить значение week or month из StatisticsDatePicker
 */
export enum ActionType {
  STATISTICS_GET_STATISTICS = "STATISTICS_GET_STATISTICS",
  STATISTICS_DELETE_STATISTICS = "STATISTICS_DELETE_STATISTICS",
  STATISTICS_UPDATE_STATISTICS = "STATISTICS_UPDATE_STATISTICS",
  STATISTICS_GET_ONE_USER_ANALITICS_BY_ID = "STATISTICS_GET_ONE_USER_ANALITICS_BY_ID",
  USER_GET_ALL_USERS = "USER_GET_ALL_USERS",
  SET_AUTH = "SET_AUTH",
  SET_ISLOADING = "SET_ISLOADING",
  SET_MONTH = "SET_MONTH",
  SET_YEAR = "SET_YEAR",
  SET_WEEK = "SET_WEEK",
  SET_TIME_STEP = "SET_TIME_STEP",
}
