import { FC, createContext, useState } from 'react';
import { IUser } from '../interfaces/stateInterface/stateInterface';


export const UserContext: any = createContext([]);


export const UserProvider: FC = ({ children }) => {

    const [user, setUser] = useState<IUser[]>([
        {
            key: '1',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test',
            project: 'teamgeist',
            userType: 'developer',
        },
        {
            key: '2',
            lastName: 'test',
            firstName: 'John',
            email: 'admin',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '3',
            lastName: 'Daniil',
            firstName: 'Zahliadov',
            email: 'daniil@gmail.com',
            project: 'teamgeist',
            userType: 'developer',
        },
        {
            key: '4',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '5',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '6',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '7',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '8',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '9',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '10',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '11',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '12',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '13',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '14',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '15',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '16',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '17',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '18',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '19',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '20',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '21',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '22',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '23',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '24',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '25',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '26',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '27',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '28',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '29',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '30',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '31',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '32',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '33',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '34',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '35',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '36',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
        {
            key: '37',
            lastName: 'Brown',
            firstName: 'John',
            email: 'test@gmail.com',
            project: 'teamgeist',
            userType: 'admin',
        },
    ]);

    return (
        <UserContext.Provider value={[user, setUser]}>
            {children}
        </UserContext.Provider>
    )
}
